### ISSUE TITLE
NPE triggered when loading storage object without attr file

### ISSUE THREAD

**Issue by greenlaw110** [osglworks/java-storage#10]
Error stack:

```
org.osgl.exception.UnexpectedIOException: File does not exists: /home/luog/p/act/samples/upload/store1/2017/04/18/844dc10d-fac9-4a43-b3c4-70319c61f0a5.attr
	at org.osgl.util.E.ioException(E.java:119)
	at org.osgl.util.IO.is(IO.java:146)
	at org.osgl.storage.impl.FileSystemService$1.transform(FileSystemService.java:142)
	at org.osgl.storage.impl.FileSystemService$1.transform(FileSystemService.java:139)
	at org.osgl.Osgl$Transformer.apply(Osgl.java:2541)
	at org.osgl.storage.impl.FileSystemService.doOperate(FileSystemService.java:119)
	at org.osgl.storage.impl.FileSystemService.doOperate(FileSystemService.java:93)
	at org.osgl.storage.impl.FileSystemService.doGetMeta(FileSystemService.java:75)
	at org.osgl.storage.impl.StorageServiceBase.getMeta(StorageServiceBase.java:337)
	at org.osgl.storage.impl.StorageServiceBase.getMeta(StorageServiceBase.java:332)
	at org.osgl.storage.impl.StorageObject.<init>(StorageObject.java:21)
	at org.osgl.storage.impl.FileObject.<init>(FileObject.java:5)
	at org.osgl.storage.impl.FileSystemService.newSObject(FileSystemService.java:126)
	at org.osgl.storage.impl.StorageServiceBase.getFull(StorageServiceBase.java:255)
	at org.osgl.storage.impl.StorageServiceBase.put(StorageServiceBase.java:294)
	at demo.upload.UploadDemo.testRemoteFetch(UploadDemo.java:47)
	at demo.upload.UploadDemoMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:413)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:220)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:42)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:445)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:187)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1245)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
fixed in 1.1.1
